### ISSUE TITLE
Update default branch for repos

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/ci#121]
Change default branch from `master` to `main`:
- [x] https://github.com/metanorma/ogc-wfs
- [x] https://github.com/metanorma/hk-ogcio-infosec-docs
- [x] https://github.com/metanorma/csa-caiq
- [x] https://github.com/metanorma/sample-ogc-discussion-paper
- [x] https://github.com/metanorma/rfc-divination-cfapi
- [x] https://github.com/metanorma/rfc-camelot-holy-grenade
- [x] https://github.com/metanorma/rfc-asciidoc-rfc
- [x] https://github.com/metanorma/rfc-asciirfc-minimal
- [x] https://github.com/metanorma/iso-690
- [x] https://github.com/metanorma/iso-8000-51
- [x] https://github.com/metanorma/iso-8000-100-ed2
- [x] https://github.com/metanorma/iso-8601-1
- [x] https://github.com/metanorma/iso-8601-2
- [x] https://github.com/metanorma/iso-19626-1
- [x] https://github.com/metanorma/iso-tc184-sc4
- [x] https://github.com/metanorma/iso-tc184-sc4-directives

Also, I have missing permission:
- [x] https://github.com/metanorma/mn-samples-standoc

Also I getting:

> ERROR: Your top-level group is over the user limit and has been placed in a read-only state.
> remote:
> remote: ========================================================================
> remote:
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

For:
- [x] https://github.com/metanorma/iso-8601-1
- [x] https://github.com/metanorma/iso-8601-2

**Comment by CAMOBAP** [comment]
Friendly reminder @ronaldtse

**Comment by ronaldtse** [comment]
@CAMOBAP I've updated the branch names and permissions for all these repos. Thanks!
