### ISSUE TITLE
"generate" workflow "Post" jobs showing "path validation error

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/ci#123]
https://github.com/Spatial-Web-Foundation/SWF-Corpus_and_IEEEP2874-D2/actions/runs/6119622323/job/16609900402
<img width="891" alt="Screenshot 2023-09-08 at 4 57 06 PM" src="https://github.com/metanorma/ci/assets/11865/d23c635a-5d9e-4c29-a82b-518c66355104">
<img width="926" alt="Screenshot 2023-09-08 at 4 57 24 PM" src="https://github.com/metanorma/ci/assets/11865/d76caff0-b965-4e06-aa16-93f148d8061b">

**Comment by CAMOBAP** [comment]
In my opinion, there is nothing critical in these warnings.

We use [`actions-mn/cache`](https://github.com/actions-mn/cache/blob/main/action.yml) which is originally designed to be universal across docker and os specific metanorma, this is why `/root` paths not exists

Let me know if I missing something or if we should create separate cache-docker action

**Comment by CAMOBAP** [comment]
@ronaldtse feel free to reopen if I missed something
