### ISSUE TITLE
Remove `.hound.yml` from repository level

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/ci#127]
Per https://github.com/metanorma/vectory/issues/6#issuecomment-1738488803 we have `.hound.yml` on organization level and should not add it in each repository

cc @ronaldtse

**Comment by ronaldtse** [comment]
@CAMOBAP let me know what needs to be done. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse nothing from your side, I just decided to cc just in case we should not go with this approach

**Comment by CAMOBAP** [comment]
Done

**Comment by ronaldtse** [comment]
Thanks!
