### ISSUE TITLE
Ruby 2.7 requires rubygems 3.4.22 in ruby-matrix.json

### ISSUE THREAD

**Issue by maxirmx** [metanorma/ci#136]
https://github.com/metanorma/ci/tree/main/.github/workflows/ruby-matrix.json

Ruby 2.7 requires rubygems 3.4.22

This is because ruby/setup-ruby GHA action installs bundler 2.4.22 for Ruby 2.7 and this version of bundler is not fully compatible with default version of rubygems (3.1.6)

ref https://github.com/lutaml/expressir/issues/141

**Comment by CAMOBAP** [comment]
Updated, and executed manually https://github.com/lutaml/expressir/actions/runs/7292820291

I don't see some 2.7 related crashes on CI, @maxirmx maybe you can point me where it fails and how verify the fix?

**Comment by maxirmx** [comment]
It is "post release" issue. It crashes on fetch from rubygems.org 

- Install clean Ruby 2.7
- Update bundler to 2.4.22
- Run gem install expressir    ==> crash

- Update rubygems to 3.4.22
- Run gem install expressir    ==> OK

**Comment by maxirmx** [comment]
Thank you, @CAMOBAP.   It works for https://github.com/metanorma/stepmod-utils

Could you please help with this file: https://github.com/glossarist/concept-model/blob/main/.github/workflows/make.yml
It has setup-ruby action inside but says that it is "autogenerated by cimas".  Not sure how to fix it.
