### ISSUE TITLE
Bundler version in ruby-matrix.json

### ISSUE THREAD

**Issue by maxirmx** [metanorma/ci#147]
I believe we need bundler version in https://github.com/metanorma/ci/blob/main/.github/workflows/ruby-matrix.json similar to rubygems version 
Options: 'version tag'/default/latest

Thank you

**Comment by CAMOBAP** [comment]
@maxirmx make sense, should I set everything to `default` at this moment?

**Comment by maxirmx** [comment]
I believe we need ```2.4.22``` for ```3.0``` and ```2.7``` and default for ```3.1``` and ```3.2```
