### ISSUE TITLE
"testing" jobs should be run according to cron daily in addition to pushes

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/ci#168]
When the Metanorma stack gets released, there may be a gap between the last success of a gem to the release date, while in between some dependency (software or workflow) may have been broken but not detected.

That's why we should add daily test builds as well as the on-demand builds.

This needs to apply to the full Metanorma stack and other related software, such as lutaml, plurimath, pubid, relaton, fontist, vectory, etc.

**Comment by CAMOBAP** [comment]
Related https://github.com/metanorma/metanorma-cli/issues/330

**Comment by CAMOBAP** [comment]
Done for repost listed by Nick
