### ISSUE TITLE
Add comment to pull request if mn-samples-* failed

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/ci#76]
For now, any changes in `metanorma-*` processor triggers [test sample workflow](https://github.com/metanorma/metanorma-build-scripts/blob/main/.github/workflows/sample-test.yml) and [test template workflow](https://github.com/metanorma/metanorma-build-scripts/blob/main/.github/workflows/template-test.yml) for corresponding `mn-samples-*` or `mn-templates-*` repository

### Proposal

It will be nice if test workflow will add a comment to the original `metanorma-*` PR if tests are failed
https://stackoverflow.com/questions/58066966/commenting-a-pull-request-in-a-github-action

@opoudjis @ronaldtse let me know if this makes sens

**Comment by ronaldtse** [comment]
@CAMOBAP this is a good idea. In Metanorma.org we have a check links action that can post an issue after the run, have a look.

**Comment by CAMOBAP** [comment]
related https://github.com/metanorma/ci/issues/43

**Comment by CAMOBAP** [comment]
Because we implemented another approach, samples compilation run as part of metanorma-* workflow this task makes no sens
