### ISSUE TITLE
Compile documents in separate jobs before sitegen

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/ci#81]
### Intro

To speed up our workflow we can do document compilation in separate jobs. The idea is described here https://code.dblock.org/2021/09/03/generating-task-matrix-by-looping-over-repo-files-with-github-actions.html also we already use this approach for mn-templates-* repos.

### Open questions

 - [x] can `metanorma site generate` reuse previously compiled documents?
 - [x] how can we fetch all resources (relaton, ietf, fonts, anything else) once before run?

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis may I ask you to have a look at open questions, maybe you have answers or some general idea about the task?

**Comment by ronaldtse** [comment]
> can metanorma site generate reuse previously compiled documents

Not right now. We have a long standing task here: https://github.com/metanorma/metanorma-cli/issues/232

> how can we fetch all resources (relaton, ietf, fonts, anything else) once before run?

I don't think that is possible. Especially Relaton entries are only known during compilation.
