### ISSUE TITLE
Don't run CI for tags on metanorma gems

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/ci#89]
### Intro

As part of the https://github.com/metanorma/metanorma-build-scripts/issues/85 I modified the workflow to no run tests twice in case of tag

### Problem

Because we skip job on the main branch in case of tag this affects our release matrix from https://github.com/metanorma/metanorma-release

The solution is not to run tests on tag events. But it still will be nice to see tags in CI history so I will check if possible to have both tag and branch labels on the same job

**Comment by CAMOBAP** [comment]
Another proposed solution to show extra badge which will show last release CI status, it seems better to me, I will prepare PR

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
