### ISSUE TITLE
update bin/gh-repo-manifest script

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/ci#99]
### Problem

Metanorma now has more than 300 repositories and sometimes we forget to update/add CI configuration in https://github.com/metanorma/ci/blob/main/cimas-config/cimas.yml

### Proposal

Use topics to classify repositories automatically, proposed list of topics (tags):

- `metanorma-site`:
  - metanorma.org
  - asciirfc.com
  - metanorma.com
- `metanorma-gem`:
  - html2doc
  - mathml2asciimath
  - omml2mathml
  - rfc2md
  - mn2pdf
  - mn2sts
  - unicode2latex
  - mn2pdf-ruby
  - mn2sts-ruby
  - stepmod2mn
  - iso690render
  - csa-ccm-tools
  - reverse_adoc
  - tex2mn
  - isodoc
  - mnconvert-ruby
  - iev
  - gb-agencies
  - bipm-data-importer
  - metanorma
  - metanorma-registry
  - metanorma-utils
  - cimas
  - lapidist
  - metanorma-plugin-lutaml
  - metanorma-plugin-datastruct
- `metanorma-jar`:
  - mn2pdf
  - mn2sts
  - mnconvert
- `metanorma-data`:
  - isoics
  - cnccs
- `metanorma-flavor`:
  - metanorma-cli
  - metanorma-csa
  - metanorma-cc
  - metanorma-iec
  - metanorma-ietf
  - metanorma-iso
  - metanorma-itu
  - metanorma-m3aawg
  - metanorma-nist
  - metanorma-ogc
  - metanorma-ribose
  - metanorma-standoc
  - metanorma-un
  - metanorma-generic
  - metanorma-iho
  - metanorma-bipm
  - metanorma-bsi
  - metanorma-ieee
  - metanorma-gb
  - metanorma-vg
  - metanorma-mpfa
- `metanorma-model`:
  - metanorma-model-csa
  - metanorma-model-cc
  - metanorma-model-iso
  - metanorma-model-itu
  - metanorma-model-m3d
  - metanorma-model-mpfa
  - metanorma-model-nist
  - metanorma-model-ogc
  - metanorma-model-rsd
  - metanorma-model-standoc
  - metanorma-model-un
  - metanorma-model-bipm
  - metanorma-model-ieee
  - metanorma-model-bsi
  - basicdoc-models
  - metanorma-requirements-models
  - metanorma-model-iho
  - metanorma-model-gb
infrastructure:
  - metanorma-release
  - metanorma-document-gh-pages
  - iso-ics-codes-scripts
  - metanorma-registry
  - ci
  - oss-guides
  style:
  - csd-style
  - csand-style
  - gbdoc-style
  - isodoc-style
  - rsd-style
  - m3d-style
  - mpfd-style
  - metanorma-ogc-style
  - metanorma-nist-style
  - metanorma-itu-style
  - metanorma-nist-style
  - metanorma-ogc-style
- `metanorma-document-dev`
  - mn-samples-cc
  - mn-samples-iec
  - mn-samples-ietf
  - mn-samples-iso
  - mn-samples-itu
  - mn-samples-ogc
  - mn-samples-un
  - mn-samples-iho
  - mn-samples-csa
  - mn-samples-nist
  - mn-samples-m3aawg
  - mn-samples-bipm
  - mn-samples-jcgm
  - mn-samples-ribose
- `metanorma-document`:
  - iso-690
  - iso-8000-51
  - iso-8000-100-ed2
  - iso-8601-1
  - iso-8601-2
  - iso-10303
  - iso-10303-2
  - iso-19115-3
  - iso-19626-1
  - iso-tc184-sc4
  - DGGS2ISO-19170
  - mn-samples-nist
  - ogc-dggs-xmi
  - hk-ogcio-infosec-docs
  - ogc-wfs
  - ogc-tcpnp
  - csa-caiq
  - bipm-si-brochure
  - isodoc-rice
- `metanorma-templates`:
  - mn-templates-cc
  - mn-templates-un
  - mn-templates-iec
  - mn-templates-ietf
  - mn-templates-iso
  - mn-templates-itu
  - mn-templates-ogc
  - mn-templates-nist
  - mn-templates-m3aawg
- `metanorma-asciirfc`:
  - rfc-divination-cfapi
  - rfc-camelot-holy-grenade
  - rfc-asciidoc-rfc
  - rfc-asciirfc-minimal
- `metanorma-frontend`:
  - metanorma-cli
  - metanorma-docker
  - packed-mn
  - chocolatey-metanorma
  - homebrew-metanorma
  - metanorma-snap
  - latexml-snap

**Comment by ronaldtse** [comment]
The metanorma-asciirfc ones should also be considered as metanorma-document (we will have to update those repos to use the latest metanorma site structure)

**Comment by CAMOBAP** [comment]
@ronaldtse may I kindly ask you for a high-level review of topic names (list are not complete yet)

I don't have permission to modify topics/tags, so how we will move further?

**Comment by CAMOBAP** [comment]
I'm not sure if this is doable at this stage because I have no permission to add topics to the repos. And probably most of our are repos don't have topics

I still think that maintain topics it's a good idea, and we should back to it some time ago

**Comment by CAMOBAP** [comment]
I will update gh-repo-manifest script to report diff and print only new repos

**Comment by CAMOBAP** [comment]
Watcher job completed
